services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    InSquare\PimcoreDeeplBundle\Service\TranslationConfig:
        arguments:
            $overwriteDocuments: '%in_square_pimcore_deepl.overwrite.documents%'
            $overwriteObjects: '%in_square_pimcore_deepl.overwrite.objects%'

    InSquare\PimcoreDeeplBundle\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']
        public: true

    InSquare\PimcoreDeeplBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Resources/'
            - '../../InSquarePimcoreDeeplBundle.php'
